name: 'weather_pipeline'
version: '1.0.0'
config-version: 2

profile: 'weather_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  weather_pipeline:
    materialized: table
