weather_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: weather_db
      user: admin
      password: password
      port: 5432
      dbname: weather
      schema: public
      threads: 1
